//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graph_Xamarin_CS_Snippets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graph_Xamarin_CS_Snippets.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member to group.
        /// </summary>
        internal static string AddMember {
            get {
                return ResourceManager.GetString("AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add XL Table.
        /// </summary>
        internal static string AddXLTable {
            get {
                return ResourceManager.GetString("AddXLTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add XL Table Row.
        /// </summary>
        internal static string AddXLTableRow {
            get {
                return ResourceManager.GetString("AddXLTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Graph Snippets.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change XL Number Format.
        /// </summary>
        internal static string ChangeXLNumFormat {
            get {
                return ResourceManager.GetString("ChangeXLNumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear selection.
        /// </summary>
        internal static string ClearSelected {
            get {
                return ResourceManager.GetString("ClearSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Event.
        /// </summary>
        internal static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        internal static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Text File.
        /// </summary>
        internal static string CreateTextFile {
            get {
                return ResourceManager.GetString("CreateTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create XL Chart.
        /// </summary>
        internal static string CreateXLChart {
            get {
                return ResourceManager.GetString("CreateXLChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Event.
        /// </summary>
        internal static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Group.
        /// </summary>
        internal static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete XL File.
        /// </summary>
        internal static string DeleteXLFile {
            get {
                return ResourceManager.GetString("DeleteXLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download File.
        /// </summary>
        internal static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter XL Table.
        /// </summary>
        internal static string FilterXLTable {
            get {
                return ResourceManager.GetString("FilterXLTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a Group.
        /// </summary>
        internal static string GetAGroup {
            get {
                return ResourceManager.GetString("GetAGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All Groups.
        /// </summary>
        internal static string GetAllGroups {
            get {
                return ResourceManager.GetString("GetAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Directs.
        /// </summary>
        internal static string GetDirects {
            get {
                return ResourceManager.GetString("GetDirects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Drive.
        /// </summary>
        internal static string GetDrive {
            get {
                return ResourceManager.GetString("GetDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Events.
        /// </summary>
        internal static string GetEvents {
            get {
                return ResourceManager.GetString("GetEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Manager.
        /// </summary>
        internal static string GetManager {
            get {
                return ResourceManager.GetString("GetManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Me.
        /// </summary>
        internal static string GetMe {
            get {
                return ResourceManager.GetString("GetMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Members.
        /// </summary>
        internal static string GetMembers {
            get {
                return ResourceManager.GetString("GetMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Messages.
        /// </summary>
        internal static string GetMessages {
            get {
                return ResourceManager.GetString("GetMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Owners.
        /// </summary>
        internal static string GetOwners {
            get {
                return ResourceManager.GetString("GetOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Photo.
        /// </summary>
        internal static string GetPhoto {
            get {
                return ResourceManager.GetString("GetPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get User Files.
        /// </summary>
        internal static string GetUserFiles {
            get {
                return ResourceManager.GetString("GetUserFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get User Groups.
        /// </summary>
        internal static string GetUserGroups {
            get {
                return ResourceManager.GetString("GetUserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get XL Range.
        /// </summary>
        internal static string GetXLRange {
            get {
                return ResourceManager.GetString("GetXLRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable to personal or work accounts.
        /// </summary>
        internal static string PersonalWorkAccess {
            get {
                return ResourceManager.GetString("PersonalWorkAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please register your app before you run this sample.
        /// </summary>
        internal static string PleaseRegister {
            get {
                return ResourceManager.GetString("PleaseRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect Worksheet.
        /// </summary>
        internal static string ProtectWorksheet {
            get {
                return ResourceManager.GetString("ProtectWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Users.
        /// </summary>
        internal static string ReadUsers {
            get {
                return ResourceManager.GetString("ReadUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        internal static string RenameFile {
            get {
                return ResourceManager.GetString("RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string ResultFail {
            get {
                return ResourceManager.GetString("ResultFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string ResultSuccess {
            get {
                return ResourceManager.GetString("ResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run selected.
        /// </summary>
        internal static string RunSelected {
            get {
                return ResourceManager.GetString("RunSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set XL Formula.
        /// </summary>
        internal static string SetXLFormula {
            get {
                return ResourceManager.GetString("SetXLFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort XL Table.
        /// </summary>
        internal static string SortXLTable {
            get {
                return ResourceManager.GetString("SortXLTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprotect Worksheet.
        /// </summary>
        internal static string UnprotectWorksheet {
            get {
                return ResourceManager.GetString("UnprotectWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Event.
        /// </summary>
        internal static string UpdateEvent {
            get {
                return ResourceManager.GetString("UpdateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update File.
        /// </summary>
        internal static string UpdateFile {
            get {
                return ResourceManager.GetString("UpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Group.
        /// </summary>
        internal static string UpdateGroup {
            get {
                return ResourceManager.GetString("UpdateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update XL Range.
        /// </summary>
        internal static string UpdateXLRange {
            get {
                return ResourceManager.GetString("UpdateXLRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload XL File.
        /// </summary>
        internal static string UploadXLFile {
            get {
                return ResourceManager.GetString("UploadXLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable to work accounts only.
        /// </summary>
        internal static string WorkAccess {
            get {
                return ResourceManager.GetString("WorkAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable to work accounts with admin rights.
        /// </summary>
        internal static string WorkAdminAccess {
            get {
                return ResourceManager.GetString("WorkAdminAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL ABS Function.
        /// </summary>
        internal static string XLABSFunction {
            get {
                return ResourceManager.GetString("XLABSFunction", resourceCulture);
            }
        }
    }
}
